var rirmap = {"1": "APNIC",
              "2": "RIPE",
              "5": "RIPE",
              "14": "APNIC",
              "23": "ARIN",
              "24": "ARIN",
              "27": "APNIC",
              "31": "RIPE",
              "36": "APNIC",
              "37": "RIPE",
              "39": "APNIC",
              "41": "AFRINIC",
              "42": "APNIC",
              "46": "RIPE",
              "49": "APNIC",
              "50": "ARIN",
              "58": "APNIC",
              "59": "APNIC",
              "60": "APNIC",
              "61": "APNIC",
              "62": "RIPE",
              "63": "ARIN",
              "64": "ARIN",
              "65": "ARIN",
              "66": "ARIN",
              "67": "ARIN",
              "68": "ARIN",
              "69": "ARIN",
              "70": "ARIN",
              "71": "ARIN",
              "72": "ARIN",
              "73": "ARIN",
              "74": "ARIN",
              "75": "ARIN",
              "76": "ARIN",
              "77": "RIPE",
              "78": "RIPE",
              "79": "RIPE",
              "80": "RIPE",
              "81": "RIPE",
              "82": "RIPE",
              "83": "RIPE",
              "84": "RIPE",
              "85": "RIPE",
              "86": "RIPE",
              "87": "RIPE",
              "88": "RIPE",
              "89": "RIPE",
              "90": "RIPE",
              "91": "RIPE",
              "92": "RIPE",
              "93": "RIPE",
              "94": "RIPE",
              "95": "RIPE",
              "96": "ARIN",
              "97": "ARIN",
              "98": "ARIN",
              "99": "ARIN",
              "100": "ARIN",
              "101": "APNIC",
              "102": "AFRINIC",
              "103": "APNIC",
              "104": "ARIN",
              "105": "AFRINIC",
              "106": "APNIC",
              "107": "ARIN",
              "108": "ARIN",
              "109": "RIPE",
              "110": "APNIC",
              "111": "APNIC",
              "112": "APNIC",
              "113": "APNIC",
              "114": "APNIC",
              "115": "APNIC",
              "116": "APNIC",
              "117": "APNIC",
              "118": "APNIC",
              "119": "APNIC",
              "120": "APNIC",
              "121": "APNIC",
              "122": "APNIC",
              "123": "APNIC",
              "124": "APNIC",
              "125": "APNIC",
              "126": "APNIC",
              "173": "ARIN",
              "174": "ARIN",
              "175": "APNIC",
              "176": "RIPE",
              "177": "LACNIC",
              "178": "RIPE",
              "179": "LACNIC",
              "180": "APNIC",
              "181": "LACNIC",
              "182": "APNIC",
              "183": "APNIC",
              "184": "ARIN",
              "185": "RIPE",
              "186": "LACNIC",
              "187": "LACNIC",
              "189": "LACNIC",
              "190": "LACNIC",
              "193": "RIPE",
              "194": "RIPE",
              "195": "RIPE",
              "197": "AFRINIC",
              "199": "ARIN",
              "200": "LACNIC",
              "201": "LACNIC",
              "202": "APNIC",
              "203": "APNIC",
              "204": "ARIN",
              "205": "ARIN",
              "206": "ARIN",
              "207": "ARIN",
              "208": "ARIN",
              "209": "ARIN",
              "210": "APNIC",
              "211": "APNIC",
              "212": "RIPE",
              "213": "RIPE",
              "216": "ARIN",
              "217": "RIPE",
              "218": "APNIC",
              "219": "APNIC",
              "220": "APNIC",
              "221": "APNIC",
              "222": "APNIC",
              "223": "APNIC"};

db.servers.find().forEach(function(doc) {
    try {
        var prefix = doc['_id'].split('.')[0];

        if (prefix in rirmap) {
            db.servers.update(
                {_id: doc['_id']},
                {$set: {rir: rirmap[prefix]}}
            );
        } else {
            db.servers.update(
                {_id: doc['_id']},
                {$set: {rir: 'other'}}
            );
        }
    } catch (e) {
    }
});
